name: Allure Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read   # required by deploy-pages@v4

jobs:
  build-allure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Allure results (composite action)
        uses: ./.github/actions/build-allure-report

      # 👉 generate static site: allure-report/
      - name: Generate Allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_report: allure-report

      # 👉 upload site artifact for Pages
      - name: Upload Pages artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report

  deploy:
    needs: build-allure
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
