name: CI

on:
  push:
    branches: ['**']
    tags-ignore: ['**']
  pull_request:

jobs:
  lint:
    name: Lint (3.12)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-lint
        with:
          python-version: '3.12'

  test:
    name: Test (3.8 - 3.13)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13']
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-test
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upload coverage to Codecov
        if: ${{ matrix.python-version == '3.12' }}
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          fail_ci_if_error: false
