name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: uv sync --dev
      - name: Black
        run: uv run black --check --line-length 120 src
      - name: Flake8
        run: uv run flake8 --max-line-length 120 src
      - name: Mypy
        run: uv run mypy --strict src
